export const buttonExperimentAbi = [
  {"inputs": [{"internalType": "address", "name": "starter_", "type": "address"}], "stateMutability": "nonpayable", "type": "constructor"},
  {"inputs": [], "name": "BLUE", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "GREEN", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "ORANGE", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "PURPLE", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "RED", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "WINDOW", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "YELLOW", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "closestCall", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "closestCallWallet", "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "deadline", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "endedAt", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "name": "factionCounts", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "finalize", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
  {"inputs": [], "name": "finalized", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
  {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "hasPressed", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "isAlive", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "lastPressedAt", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "lastPresser", "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "press", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
  {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "pressFaction", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "pressNumber", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "pressRemaining", "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "resetTimer", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
  {"inputs": [], "name": "start", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
  {"inputs": [], "name": "started", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "startedAt", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "starter", "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "timeLeft", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "timerResetCount", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"inputs": [], "name": "totalPresses", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
  {"anonymous": false, "inputs": [{"indexed": true, "internalType": "uint256", "name": "endedAt", "type": "uint256"}, {"indexed": false, "internalType": "uint256", "name": "totalPresses", "type": "uint256"}, {"indexed": false, "internalType": "uint8", "name": "closestCall", "type": "uint8"}], "name": "ExperimentFinalized", "type": "event"},
  {"anonymous": false, "inputs": [{"indexed": true, "internalType": "uint256", "name": "timestamp", "type": "uint256"}, {"indexed": false, "internalType": "uint256", "name": "deadline", "type": "uint256"}], "name": "ExperimentStarted", "type": "event"},
  {"anonymous": false, "inputs": [{"indexed": true, "internalType": "address", "name": "presser", "type": "address"}, {"indexed": false, "internalType": "uint8", "name": "remaining", "type": "uint8"}, {"indexed": false, "internalType": "uint8", "name": "faction", "type": "uint8"}, {"indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256"}, {"indexed": false, "internalType": "uint256", "name": "pressNumber", "type": "uint256"}], "name": "Pressed", "type": "event"},
  {"anonymous": false, "inputs": [{"indexed": true, "internalType": "address", "name": "admin", "type": "address"}, {"indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256"}, {"indexed": false, "internalType": "uint256", "name": "newDeadline", "type": "uint256"}, {"indexed": false, "internalType": "uint256", "name": "resetNumber", "type": "uint256"}], "name": "TimerReset", "type": "event"},
  {"inputs": [], "name": "AlreadyFinalized", "type": "error"},
  {"inputs": [], "name": "AlreadyPressed", "type": "error"},
  {"inputs": [], "name": "AlreadyStarted", "type": "error"},
  {"inputs": [], "name": "ExperimentEnded", "type": "error"},
  {"inputs": [], "name": "ExperimentNotAlive", "type": "error"},
  {"inputs": [], "name": "ExperimentStillAlive", "type": "error"},
  {"inputs": [], "name": "InvalidTimestamp", "type": "error"},
  {"inputs": [], "name": "NotStarted", "type": "error"},
  {"inputs": [], "name": "OnlyStarter", "type": "error"},
  {"inputs": [], "name": "ZeroAddress", "type": "error"}
] as const;
